### ISSUE TITLE
Julia VS Code extension crashes with “Endpoint is not running, the current state is closed

### ISSUE THREAD

**Issue by josemanuel22** [julia-vscode/julia-vscode#3824]
When using the Julia extension in VS Code (v1.140.2) in tmux, I encountered a crash in the language server. The error message indicates that the endpoint is no longer running:
```
Error: Some Julia code in the VS Code extension crashed
└ @ VSCodeServer ~/.vscode-server/extensions/julialang.language-julia-1.140.2/scripts/error_handler.jl:15
ERROR: Endpoint is not running, the current state is closed.
```

This causes the language server to stop responding and requires a full restart of the tmux session.

**Comment by albertomercurio** [comment]
I also have the same problem, using zellij rather than tmux. I can't start a simulation and then leave.

**Comment by krcools** [comment]
I see this also happen, quite often recently. Mostly when the session is unatttended, but at times also when the vscode client is attached.

**Comment by pfitzseb** [comment]
What version of the extension are you seeing this on? The Julia session shouldn't be crashing anymore; you should get a `Lost connection to the editor. You can use the 'Julia: Connect External REPL' command to reconnect.` message instead.

**Comment by krcools** [comment]
The Julia vscode extension is on v1.215.2.

To be exact, when I use Alt-J Alt-O to open the terminal with the tmux session hosting the Julia REPL, I see:

```
julia> ┌ Error: Some Julia code in the VS Code extension crashed
└ @ VSCodeServer ~/.vscode-server/extensions/julialang.language-julia-1.215.2/scripts/error_handler.jl:5
ERROR: TransportError: Endpoint closed
Stacktrace:
 [1] get_next_message(endpoint::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint, VSCodeServer.JSON.Serializations.StandardSerialization, VSCodeServer.JSONRPC.ContentLengthFraming}; token::Nothing)
   @ VSCodeServer.JSONRPC ~/.vscode-server/extensions/julialang.language-julia-1.215.2/scripts/packages/JSONRPC/src/core.jl:629
 [2] get_next_message(endpoint::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint, VSCodeServer.JSON.Serializations.StandardSerialization, VSCodeServer.JSONRPC.ContentLengthFraming})
   @ VSCodeServer.JSONRPC ~/.vscode-server/extensions/julialang.language-julia-1.215.2/scripts/packages/JSONRPC/src/core.jl:610
 [3] macro expansion
   @ ~/.vscode-server/extensions/julialang.language-julia-1.215.2/scripts/packages/VSCodeServer/src/VSCodeServer.jl:179 [inlined]
 [4] macro expansion
   @ ./task.jl:662 [inlined]
 [5] (::VSCodeServer.var"#205#206"{Bool, var"#5#6"{String}, Base.PipeEndpoint})()
   @ VSCodeServer ~/.vscode-server/extensions/julialang.language-julia-1.215.2/scripts/packages/VSCodeServer/src/VSCodeServer.jl:178

Pane is dead (status 1, Wed 27 22::27:31 2026)
```

Using Julia: Connect to External REPL does not fix this and results in a notification in vscode that reads:

```
Start a Julia session and execute the code copied into your clipboard by the button below into it.
```

**Comment by krcools** [comment]
Sorry, just realised I've been very silly here. Will try the suggestion from the notification and report back....

**Comment by pfitzseb** [comment]
That won't work from that state, the Julia session did actually crash. Will fix.

**Comment by pfitzseb** [comment]
Fixed by https://github.com/julia-vscode/julia-vscode/pull/4098.

**Comment by h-spiess** [comment]
this fix has been on main for roughly a month. any idea when it will enter the pre-release version? I've been struggling with this issue since :)

**Comment by pfitzseb** [comment]
Today :)

**Comment by h-spiess** [comment]
I've switched to the VSCode pre-release version in the VSCode UI, which gives me v1.218.1. The error still occurs. This is all run in a persistent tmux sessions started from the extension.

Thanks :)

```
julia> ┌ Error: Some Julia code in the VS Code extension crashed
└ @ VSCodeServer /mnt/data/ni/spiess/vscode-server-local/.vscode-server/extensions/julialang.language-julia-1.218.1/scripts/error_handler.jl:5
ERROR: Endpoint is not running, the current state is status_closed.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:44
 [2] check_dead_endpoint!
   @ /mnt/data/ni/spiess/vscode-server-local/.vscode-server/extensions/julialang.language-julia-1.218.1/scripts/packages/JSONRPC/src/core.jl:728 [inlined]
 [3] send_success_response(endpoint::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint, VSCodeServer.JSON.Serializations.StandardSerialization, VSCodeServer.JSONRPC.ContentLengthFraming}, original_request::VSCodeServer.JSONRPC.Request, result::Any)
   @ VSCodeServer.JSONRPC /mnt/data/ni/spiess/vscode-server-local/.vscode-server/extensions/julialang.language-julia-1.218.1/scripts/packages/JSONRPC/src/core.jl:653
 [4] dispatch_msg(x::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint, VSCodeServer.JSON.Serializations.StandardSerialization, VSCodeServer.JSONRPC.ContentLengthFraming}, dispatcher::VSCodeServer.JSONRPC.MsgDispatcher, msg::VSCodeServer.JSONRPC.Request)
   @ VSCodeServer.JSONRPC /mnt/data/ni/spiess/vscode-server-local/.vscode-server/extensions/julialang.language-julia-1.218.1/scripts/packages/JSONRPC/src/typed.jl:110
 [5] dispatch_msg(conn_endpoint::Base.RefValue{Union{Nothing, VSCodeServer.JSONRPC.JSONRPCEndpoint}}, msg_dispatcher::VSCodeServer.JSONRPC.MsgDispatcher, msg::VSCodeServer.JSONRPC.Request, is_dev::Bool)
   @ VSCodeServer /mnt/data/ni/spiess/vscode-server-local/.vscode-server/extensions/julialang.language-julia-1.218.1/scripts/packages/VSCodeServer/src/VSCodeServer.jl:119
 [6] (::VSCodeServer.var"#207#208"{VSCodeServer.JSONRPC.MsgDispatcher, VSCodeServer.JSONRPC.Request, Bool, var"#6#7"{var"#8#9"{String}}})()
   @ VSCodeServer /mnt/data/ni/spiess/vscode-server-local/.vscode-server/extensions/julialang.language-julia-1.218.1/scripts/packages/VSCodeServer/src/VSCodeServer.jl:186
```

**Comment by pfitzseb** [comment]
Missed a branch in the original fix. https://github.com/julia-vscode/julia-vscode/pull/4114 should cover everything.
