### ISSUE TITLE
still on 1.144.2: TestItems testing stuck on (Queued)

### ISSUE THREAD

**Issue by NilsNiggemann** [julia-vscode/julia-vscode#3832]
I am referring to this issue
https://github.com/julia-vscode/julia-vscode/issues/3817
For me the problem seems to be exactly the same, i.e. tests get stuck. There seems to be no noteworthy output in the test item control:

```
[ Info: Starting test item controller on Julia 1.11.4
  Activating project at `~/.vscode-server/extensions/julialang.language-julia-1.144.2/scripts/environments/testitemcontroller/v1.11`
[ Info: Creating new test run
[ Info: We need 1 procs, there are 0 processes, of which 0 are idle.
[ Info: New env, lets figure out whether we need to precompile the test environment
[ Info: Julia version is new enough
[ Info: Launching new test process
```

I have also tried this on Julia 1.11.5 with the same problem. I am using VsCode version 1.100.3

on the older version 1.127.2 the issue is absent.

**Comment by davidanthoff** [comment]
Is the code/package that triggers that public so that I could try it?

**Comment by davidanthoff** [comment]
Can you try again with pre-release version v1.145 that I just published?

**Comment by NilsNiggemann** [comment]
Hi, sorry for the late reply!

The package is public, see the master branch of this repo: https://github.com/NilsNiggemann/GreenFunctionMonteCarlo.jl

I have just tried to run it with the pre-release. It still hangs, but this time I noticed an output "Julia Test Process [some long uuid]"
In this output I at least find an error message:

```
ERROR: can not merge projects
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/Pkg/src/Types.jl:68
 [2] activate(pkg::String; allow_reresolve::Bool)
   @ TestItemServer.TestEnv ~/.vscode-server/extensions/julialang.language-julia-1.145.1/scripts/packages/TestItemControllers/packages/TestEnv/src/julia-1.11/activate_set.jl:43
 [3] activate
   @ ~/.vscode-server/extensions/julialang.language-julia-1.145.1/scripts/packages/TestItemControllers/packages/TestEnv/src/julia-1.11/activate_set.jl:9 [inlined]
 [4] activate_env_request(params::TestItemServer.TestItemServerProtocol.ActivateEnvParams, state::TestItemServer.TestProcessState{var"#1#2"}, token::TestItemServer.CancellationTokens.CancellationToken)
   @ TestItemServer ~/.vscode-server/extensions/julialang.language-julia-1.145.1/scripts/packages/TestItemControllers/testprocess/TestItemServer/src/TestItemServer.jl:551
 [5] dispatch_msg(x::TestItemServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, msg::TestItemServer.JSONRPC.Request, context::TestItemServer.TestProcessState{var"#1#2"})
   @ TestItemServer ~/.vscode-server/extensions/julialang.language-julia-1.145.1/scripts/packages/TestItemControllers/packages/JSONRPC/src/typed.jl:114
 [6] (::TestItemServer.var"#34#36"{TestItemServer.TestProcessState{var"#1#2"}, TestItemServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, TestItemServer.JSONRPC.Request})()
   @ TestItemServer ~/.vscode-server/extensions/julialang.language-julia-1.145.1/scripts/packages/TestItemControllers/testprocess/TestItemServer/src/TestItemServer.jl:710
```

**Comment by davidanthoff** [comment]
I am fairly positive that when you are getting the `ERROR: can not merge projects` error message, the root cause is unrelated to the test item trouble, but instead just due to a project situation where the test environment can't be created. I'll try to add more useful error messages for this, but in the meantime, could you try to _not_ use a custom project before you run the test items?

**Comment by davidanthoff** [comment]
Ok, I think I need to understand in some detail what exactly the env situation is when things don't work right now. Can you describe what kind of Project.toml and Manifest.toml files you have in the package folder? And then also what you have as the active project in the VS Code window from which you are running the tests?

I'm also adding a new feature to output much more detail about the project configuration that the test runner is detecting, I'm going to push that soon.

**Comment by theabhirath** [comment]
> Ok, I think I need to understand in some detail what exactly the env situation is when things don't work right now. Can you describe what kind of Project.toml and Manifest.toml files you have in the package folder? And then also what you have as the active project in the VS Code window from which you are running the tests?

In the package folder, I just have a regular Project.toml for the package with dependencies, and then in the test folder I have a separate Project.toml for tests that depends only on the package, Tests, TestItems, TestItemRunner and Documenter (to run doctests). The active project in the VS Code window is the package itself. This is what was working on v127.1.2.

**Comment by theabhirath** [comment]
Ummm...I'm not sure what changed, but I'm not able to reproduce it anymore!

**Comment by MilesCranmer** [comment]
Hitting possibly the same error in https://github.com/julia-vscode/TestItemRunner.jl/issues/112. Anybody have a workaround? Even a hack is useful... Have been slowed down a lot by this not working

**Comment by MilesCranmer** [comment]
Ok I was able to hack around this by downgrading to 1.127.2.

<img width="575" height="214" alt="Image" src="https://github.com/user-attachments/assets/7746c36b-a7d3-4ca1-b86d-2159844691ef" />

Doesn't seem there are that many old versions listed so I am not sure when this specifically broke. I'm assuming it was some change around the chain of these issues https://github.com/julia-vscode/julia-vscode/issues/3814?

**Comment by MilesCranmer** [comment]
@davidanthoff Not sure if this helps but I saw the following error in the Julia LS logs:

```julia
┌ Error: Some Julia code in the VS Code extension crashed
└ @ Main ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/error_handler.jl:15
ERROR: DerivedFunctionException: Error encountered while executing derived function:
type Nothing has no field content_hash

------ Salsa Trace -----------------
[1] @derived derived_testenv(::Runtime, JuliaWorkspaces.URIs2.URI("file", "", "/Users/mcranmer/PermaDocuments/SymbolicRegressionMonorepo/SymbolicRegression.jl/src/Dataset.jl", nothing, nothing)::JuliaWorkspaces.URIs2.URI)
------------------------------------

Stacktrace:
  [1] getproperty(x::Nothing, f::Symbol)
    @ Base ./Base.jl:49
  [2] var"%%__user_derived_testenv"(rt::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, uri::JuliaWorkspaces.URIs2.URI)
    @ JuliaWorkspaces ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/JuliaWorkspaces/src/layer_testitems.jl:132
  [3] _memoized_lookup_internal(runtime::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_testenv), Tuple{JuliaWorkspaces.URIs2.URI}})
    @ Salsa._DefaultSalsaStorage ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/Salsa/src/default_storage.jl:261
  [4] memoized_lookup(rt::Salsa._TopLevelRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, dependency_key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_testenv), Tuple{JuliaWorkspaces.URIs2.URI}})
    @ Salsa ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/Salsa/src/runtime_generic.jl:20
  [5] memoized_lookup_unwrapped
    @ ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/Salsa/src/runtime_generic.jl:43 [inlined]
  [6] derived_testenv(rt::Salsa._TopLevelRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, uri::JuliaWorkspaces.URIs2.URI)
    @ JuliaWorkspaces ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/Salsa/src/derived_macro.jl:109
  [7] get_test_env(jw::JuliaWorkspaces.JuliaWorkspace, uri::JuliaWorkspaces.URIs2.URI)
    @ JuliaWorkspaces ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/JuliaWorkspaces/src/public.jl:275
  [8] julia_get_test_env_request(params::LanguageServer.GetTestEnvRequestParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint, JSON.Serializations.StandardSerialization})
    @ LanguageServer ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/LanguageServer/src/requests/testing.jl:2
  [9] (::LanguageServer.var"#108#109"{typeof(LanguageServer.julia_get_test_env_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint, JSON.Serializations.StandardSerialization}, params::LanguageServer.GetTestEnvRequestParams, token::CancellationTokens.CancellationToken)
    @ LanguageServer ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/LanguageServer/src/languageserverinstance.jl:314
 [10] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint, JSON.Serializations.StandardSerialization}, dispatcher::JSONRPC.MsgDispatcher, msg::JSONRPC.Request)
    @ JSONRPC ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/JSONRPC/src/typed.jl:68
 [11] run(server::LanguageServerInstance; timings::Vector{Any})
    @ LanguageServer ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/LanguageServer/src/languageserverinstance.jl:474
 [12] run(server::LanguageServerInstance)
    @ LanguageServer ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/packages/LanguageServer/src/languageserverinstance.jl:348
 [13] top-level scope
    @ ~/.cursor/extensions/julialang.language-julia-1.149.2-universal/scripts/languageserver/main.jl:189
 [14] include(mod::Module, _path::String)
    @ Base ./Base.jl:562
 [15] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:323
 [16] _start()
    @ Base ./client.jl:531
[Info  - 18:14:35] Connection to server got closed. Server will restart.
true
[Error - 18:14:35] Server process exited with code 1.
```

Maybe the Julia language server is crashing and this shows up as hanging tests?

**Comment by davidanthoff** [comment]
I think this should be resolved with the latest prerelease version. Please open a new issue if you still run into that.
